const mongoose = require('mongoose');

module.exports = mongoose.Schema({
    created: Date,
    createdBy: Number,
    coords: String,
    stingers: Number,
    priestess: Number,
    praetor: Number,
    scout: Number,
    ranger: Number,
    guard: Number,
    triari: Number,
    arbalist: Number,
    ballista: Number,
    galley: Number,
    minStingers: Number,
    minPriestess: Number,
    minPraetor: Number,
    minScout: Number,
    minRanger: Number,
    minGuard: Number,
    minTriari: Number,
    minArbalist: Number,
    minBallista: Number,
    minGalley: Number,
    comments: String,
    isWater: Boolean,
});